services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user
    expose:
      - 5432
  scraper:
    build:
      context: ./scraping
    depends_on:
      - database
    environment:
      DB_URI: postgresql://user:user@database:5432/user
      # DB_URI: postgresql://user:user@172.18.0.2:5432/user