services:
  server:
    build:
      context: ./server
    env_file:
      - ./db.env
    expose:
      - 8080
  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - server
