# Use the official Golang image as a base image
FROM golang:1.21-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the entire application code to the container
COPY . .

# Download dependencies
RUN go mod download

# Build the Go application
RUN go build -o main .

# Expose port 8080 for the application to listen on
EXPOSE 8080

# Command to run the executable
CMD ["./main"]
